# Test your FastAPI endpoints

POST http://localhost:8000/employees/create
Content-Type: application/json

{
  "email" : "alondot@gmail.com",
  "role" : "employee",
  "first_name" : "aaron",
  "last_name" : "londot",
  "hire_date" :  "2025-04-12"
}

