# Test your FastAPI endpoints

POST http://localhost:8000/employees/create
Content-Type: application/json

{
  "email" : "theo.yla@gmail.com",
  "role" : "manager",
  "first_name" : "theo",
  "last_name" : "yolandia",
  "hire_date" :  "2026-04-12"
}

####

GET http://localhost:8000/employees/get?limit=2
Content-Type: application/json
